name             "rails_app"
maintainer       "Zooniverse.org"
maintainer_email "ed@zooniverse.org"
license          "Apache 2.0"
description      "Rails configuration"
version          "0.2.0"

depends          "ruby_build"
depends          "rbenv"
depends          "nginx-zoo"
depends          "unicorn"
